name: JS CI

on:
  push:
    branches: [ master,develop ,*]
  pull_request:
    branches: [ master,develop ]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install jasmine-node -g
      - run: jasmine-node .


  Rejeted:
    runs-on: ubuntu-latest
    if: ${{failure()}}
    needs: [build]
    

    steps:
    - name: checkout
      uses: actions/checkout@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: push 
      run: |
        git config --global user.email "puaud.christopher@outlook.fr"
        git config --global user.name "christopuaud"
        git commit -m "build no ${{github.run_number}} rejeted."
        git revert HEAD