name: JS CI

on:
  push:
    branches: [ master,develop ]
  pull_request:
    branches: [ master,develop ]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install jasmine-node -g
      - run: jasmine-node .

  success:
    runs-on: ubuntu-latest
    if: ${{success()}}
    needs: [build]
    

    steps:
    - name: checkout
      uses: actions/checkout@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: push 
      run: |
        git config --global user.email "ngdorian0@gmail.com"
        git config --global user.name "koalanoir"
        git checkout -b master
        git add *
        git commit -m "build  ${{github.run_number}} success."
        git push https://github.com/christopuaud/javascrip master
  Rejeted:
    runs-on: ubuntu-latest
    if: ${{failure()}}
    needs: [build]
    

    steps:
    - name: checkout
      uses: actions/checkout@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: push 
      run: |
        git config --global user.email "ngdorian0@gmail.com"
        git config --global user.name "koalanoir"
        git checkout -b rejeted-${{github.run_number}}
        git add *
        git commit -m "build no ${{github.run_number}} rejeted."
        git push https://github.com/christopuaud/javascrip rejeted-${{github.run_number}}
        git checkout -b develop
        git revert HEAD